# -*- coding: utf-8 -*-
"""Dicom.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12IlWMjnxSOMU21jJ7Q1bNsdyAkqAlaFV

#### Digital Imaging and Communications in Medicine (DICOM) Standard :
"""

from pathlib import Path
import pydicom
import matplotlib.pyplot as plt
import SimpleITK as sitk

dicom_file = pydicom.read_file("/content/ID_0000_AGE_0060_CONTRAST_1_CT.dcm")
dicom_file

dicom_file[0x0028, 0x0010]

dicom_file.Rows

ct_img = dicom_file.pixel_array
plt.figure()
plt.imshow(ct_img)

plt.imshow(ct_img, cmap="gray")

path_to_mri = Path("/content/mri_data")

all_files = list(path_to_mri.glob("*"))
all_files

mri_data = []

for path in all_files:
  data = pydicom.read_file(path)
  mri_data.append(data)

for slice in mri_data[:5]:
  print(slice.SliceLocation)

mri_data = sorted(mri_data, key=lambda slice: slice.SliceLocation)

for slice in mri_data[:5]:
  print(slice.SliceLocation)

"""#### Create list of Pixel Arrays:"""

pixel_data = []

for slice in mri_data:
  pixel_data.append(slice.pixel_array)

fig, axis = plt.subplots(3, 3, figsize=(12, 12))

slice_counter = 0

for i in range(3):
  for j in range(3):
    axis[i][j].imshow(pixel_data[slice_counter])
    slice_counter += 1

series_ids = sitk.ImageSeriesReader.GetGDCMSeriesIDs("/content/mri_data")
series_ids

series_filenames = sitk.ImageSeriesReader.GetGDCMSeriesFileNames("/content/mri_data", series_ids[0])
series_filenames

series_reader = sitk.ImageSeriesReader()
series_reader.SetFileNames(series_filenames)

image_data = series_reader.Execute()

mri_images = sitk.GetArrayFromImage(image_data)

mri_images.shape

fig, axis = plt.subplots(3, 3, figsize=(12, 12))

slice_counter = 0

for i in range(3):
  for j in range(3):
    axis[i][j].imshow(mri_images[slice_counter], cmap="gray")
    slice_counter += 1

