# -*- coding: utf-8 -*-
"""PyTorch-Tensor-Operationsipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WeUu4LTfDbT1N8W5pODmVUfFT7iP_qux
"""

import torch
import numpy as np

ts = torch.arange(0,9).reshape(3,3)
ts[:2][:1]

type(ts[2][2])

ts

ts[:,2:]

ts_2 = torch.arange(0, 10)
ts_2

ts_2.view(2, -1)

a = torch.tensor([1., 2., 3., 4.])
b = torch.tensor([5., 6., 7., 8.])
c = a + b
d = torch.add(a, b)
print(c)
print(d)

a.mul(b)

a

a.mul_(b)
a

"""#### Dot product :"""

a.dot(b)

"""#### Matrix Multiplication :"""

a = torch.tensor([[1], [2]])
a.shape

b = torch.tensor([[2, 1]])
b.shape

a @ b

torch.mm(a, b)

"""#### L2 (Euclidean) Norm :"""

a.numel()

a = a.type(torch.float64)
a.norm()

a


